spring.application.name=personal-identity
server.port=${PORT}

spring.data.mongodb.uri=${DB_URL}
spring.data.mongodb.database=personal-identity

spring.web.cors.allowed-origins=http://localhost:8080, https://personal-identity-nine.vercel.app/
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
spring.web.cors.allowed-headers=*